### ISSUE TITLE
Create Menu not working, only mouse pointer appear and get stuck

### ISSUE THREAD

**Issue by bozoweed** [BryceCanyonCounty/bcc-ranch#100]
all in the title 

i have try to take release , code , other project ( from the merge request ), update feather-menu, set me admin , but nothing get work, i can't see menu but seen the mouse cursor and player is freezed.

**Comment by bozoweed** [comment]
also bcc-stables is working great so feather-menu is working , i don't know why is not working , i have try to take peace of code frome bcc-ranch but nothing have changed

**Comment by JusCampin** [comment]
Check your load order. Here's mine as an example. I just created a ranch using `/createRanch` command.
![image](https://github.com/user-attachments/assets/21ab340d-0697-40c8-87c5-2dd3bac5deb6)

**Comment by iseeyoucopy** [comment]
Have you tried to put on dev mode to see the console prints?

**Comment by bozoweed** [comment]
yes only have print that i have no ranch , should i see more ?

**Comment by bozoweed** [comment]
i can provide a little record of the issue and console from server and client side , can  may be provide you better information

**Comment by bozoweed** [comment]
i all ready try your merge request ^^'  

but i can try again ofc :)

**Comment by bozoweed** [comment]
Appear that was the boot order for ressources ^^
