### ISSUE TITLE
having an issue

### ISSUE THREAD

**Issue by jamiemc71** [BryceCanyonCounty/bcc-ranch#14]
when i do /createranch i get the menu come up. i can fill in all the info apart from set owner. soon as i click that option the menu closes everytime.

any ideas?

thanks

**Comment by jakeyboi1** [comment]
Try this. Reinstall bcc-ranch entirely meaning also delete the ranch db. After the fresh install boot your server up, and after you select your character and load in fully then try it, and let me know

**Comment by jamiemc71** [comment]
> Try this. Reinstall bcc-ranch entirely meaning also delete the ranch db. After the fresh install boot your server up, and after you select your character and load in fully then try it, and let me know

that did the trick thank you sir :)
