### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by Phobie53** [BryceCanyonCounty/bcc-ranch#34]
🌼 Storage have the same capacity than a player inventory, with the logic of "storage" like banking and others, it need to have no maximum quantity🌼

🧰 Employee have individual storage, it's not shared 🧰

🐷 If an animal capacity is 55/50n it's not sold at the maximum price 🐷

❌ The "repair food" mission is bugged, with a girl character, it freeze, unable to start and the player is forced to disconnect ❌

🐴 Animals are not in the position saved, they appear on the road 🐴

**Comment by jakeyboi1** [comment]
Are you on the most up to date version? I believe I fixed the maximum price bug a while back. Also what do you mean by animal positions arent saved? What mission do they appear on the road in?

**Comment by Phobie53** [comment]
Yes I just downloaded the latest version yesterday. I saw that fix in the code for the maximum price some days ago too. But my users still reported me that bug yesterday (after I updated the plugin and restarted the server).

Animals are on the road (100 meters away from the paddock) instead of being inside the paddock where we saved the location.

**Comment by jakeyboi1** [comment]
> Yes I just downloaded the latest version yesterday. I saw that fix in the code for the maximum price some days ago too. But my users still reported me that bug yesterday (after I updated the plugin and restarted the server).
> 
> Animals are on the road (100 meters away from the paddock) instead of being inside the paddock where we saved the location.

So I believe you are refferring to the wandering animals that are spawning. They do not spawn in a set location they spawn randomly across the ranch and roam.

**Comment by jakeyboi1** [comment]
Closing this issue as all of these issues have been fixed.
