### ISSUE TITLE
payments for selling and milking

### ISSUE THREAD

**Issue by jamiemc71** [BryceCanyonCounty/bcc-ranch#45]
hey there i got this working in the end,
,however im having some issues,

people cant milk there cows when pressing the prompt
and when people sell there cows pigs etc there not getting paid for it despite it saying they where.

can you please help me with this issue.

look forward to hearing from you,
thanks jamie

**Comment by jakeyboi1** [comment]
Sounds like something is wrong with your install. Try a fresh install. I know milking is working as I tested it the day before yesterday😅. Lemme know if a fresh install fixes

**Comment by jamiemc71** [comment]
> Sounds like something is wrong with your install. Try a fresh install. I know milking is working as I tested it the day before yesterday😅. Lemme know if a fresh install fixes

hey. thanks for the reply. i have reinstalled it and the milking option is just not right, you click on milk then go to the cow and it freezes the player on the spot forcing them to restart the game.

**Comment by jamiemc71** [comment]
@jakeyboi1 just an update for you. the payment side of it is now working after updating but the milking side still does now.

it gives the option to milk them but then does nothing.

**Comment by jakeyboi1** [comment]
> @jakeyboi1 just an update for you. the payment side of it is now working after updating but the milking side still does not.
> 
> it gives the option to milk them but then does nothing.

Probably missing or incorrect install of bcc-minigames if I were to guess

**Comment by jamiemc71** [comment]
> > @jakeyboi1 just an update for you. the payment side of it is now working after updating but the milking side still does not.
> > it gives the option to milk them but then does nothing.
> 
> Probably missing or incorrect install of bcc-minigames if I were to guess

i have just updated the minigame and will report back :)

**Comment by jamiemc71** [comment]
@jakeyboi1 update for you. fresh install of the minigame and a fresh copy of the ranch and still milking doesnt work.

they press G and it brings up the mouse arrow but thats it :(

**Comment by jakeyboi1** [comment]
> @jakeyboi1 update for you. fresh install of the minigame and a fresh copy of the ranch and still milking doesnt work.
> 
> they press G and it brings up the mouse arrow but thats it :(

Can you join the bcc discord and open a thread there? its just easier to communicate than over github lol heres the invite link: https://discord.gg/VrZEEpBgZJ
