### ISSUE TITLE
Missing comma in config.lua

### ISSUE THREAD

**Issue by Kingsman40** [BryceCanyonCounty/bcc-ranch#63]
In the config.lua, if you're getting an error about RanchAnimalSetup, most likely the issue is a missing comma after `FeedCoolDown =900`.

It should have a comma after it `FeedCooldDown = 900,`

Once I added the comma, the error went away.

**Comment by AndrewR3K** [comment]
This has been fixed already. Please make sure to update. Thanks!

![image](https://github.com/BryceCanyonCounty/bcc-ranch/assets/10902965/50c0dd23-69cf-4df1-9814-06328a07cbf9)
