### ISSUE TITLE
createranch alone + informations on how to use

### ISSUE THREAD

**Issue by Phobie53** [BryceCanyonCounty/bcc-ranch#9]
Hello,

I am very interested in this plugin. But when I'm alone on the serveur and use the createranch command. I can't set myself as owner I am not in the list. Is it possible to list every players in the server ? So I can test the plugin alone on my dev server before use it in production.

And is it possible to make a "how to" ? Because I added a friend as owner in the ranch, but he had no prompt to open the ranch menu.

Thanks for your work ! 🙏

**Comment by jakeyboi1** [comment]
It lists every player in the server, if you are encountering an issue with it not showing you in the server it is something on your end as myself, and 2 others I have watched while streaming thier screens did not have the issue. Have you changed anything, and provide the exact steps you did when you got the issue? A how to is a good idea, will make one when I have time too. As for your friend not having a prompt it sounds like you didnt read the readme file.

**Comment by Phobie53** [comment]
Strange I'm not in the list, because I'm in the list of the VORP_Admin menu.

I didn't changed anything in the code. At the moment I was trying to figure out why I'm not in the list, and on the "bcc-ranch:GetPlayers" server event, the PlayersTable var is empty when I'm alone on the server.

**Comment by jakeyboi1** [comment]
Reinstall the script again make sure you have all the dependencies, and test again. Also provide the exact steps you did when you got the error

**Comment by Phobie53** [comment]
I already resintalled the whole script with your latest upgrades.
I got  every dependencies loaded (yesterday I did not, but I had error message in the server console).

![image](https://github.com/BryceCanyonCounty/bcc-ranch/assets/6780510/c7035056-aa5c-46db-b64f-e62f4dcdde84)
That's my console log when I load the script, an issue with the versioner but the menu to create a ranch is working so I guess it's not blocking the rest. 

By the way I updated my previous message with a bit more informations

**Comment by jakeyboi1** [comment]
Hmmm yea must be something to do with your char I suppose since no one else has had this happen. Unless this happens to someone else I'm pretty sure its just a niche issue. Also the prompt does show up to open the ranch menu?

**Comment by Phobie53** [comment]
Yeah that's why I think the link to vorp_character-lua or this error message is not a big issue since it's working with "normal" char.
But with the database line I showed you, I still have non prompt and nothing happen when I press G.

But I Guess it's the same issue, I'm not detected as a "player" for the script.

**Comment by jakeyboi1** [comment]
Its weird as this scripts method for detecting players is pulled from vorp_admin lol. Must just be something with your char. I know the new lua version of character works. Maybe try renaming vorp_characters-lua file to vorp_characters then in the ranch manifest put it back as vorp_character. Not sure but not naming vorp_character-lua to vorp_characters may be causing exporting issues

**Comment by Phobie53** [comment]
Hello,

Even renaming my vorp_character-lua into vorp_character, and changing my "group" role from "admin" to "user" into the characters table, I'm still not in the list when I try to create a ranch. And still have no prompt when I'm in the ranch. I got multiple char as admin on my account maybe that can help ?

(I still see myself in the vorp_admin menu)

**Comment by jakeyboi1** [comment]
> Hello,
> 
> Even renaming my vorp_character-lua into vorp_character, and changing my "group" role from "admin" to "user" into the characters table, I'm still not in the list when I try to create a ranch. And still have no prompt when I'm in the ranch. I got multiple char as admin on my account maybe that can help ?
> 
> (I still see myself in the vorp_admin menu)

You set yourself admin in config not db. Can you try making a new char and seeing if it works on the new char?

**Comment by Phobie53** [comment]
Ok so, with a new char, it's working I can see myself in the list of owners so I can create a ranch. But now I still have the issue with no prompt bottom right asking me to press "G" to get the ranch menu 🤔

**Comment by jakeyboi1** [comment]
> Ok so, with a new char, it's working I can see myself in the list of owners so I can create a ranch. But now I still have the issue with no prompt bottom right asking me to press "G" to get the ranch menu 🤔

ok so it was just that character that was the issue not the script. Also you have to leave and rejoin the server for the prompt to show up

**Comment by Phobie53** [comment]
![image](https://github.com/BryceCanyonCounty/bcc-ranch/assets/6780510/6ce9bf41-e015-481c-80e2-35a6abbd8530)
Thanks a lot for your help 🙏

**Comment by Phobie53** [comment]
Sorry, opening this issue again, when I logged back on the server I still not in the list of potential owner (nor another admin friend), and have no tooltip to open the ranch menu (I was connected with the last character I created and was working before). The problem is the same, it's working once I created my character, but I restarted the server, then ensure : "bcc-utils, bcc-minigames, bcc-ranch" and have nothing on this character

**Comment by jakeyboi1** [comment]
> Sorry, opening this issue again, when I logged back on the server I still not in the list of potential owner (nor another admin friend), and have no tooltip to open the ranch menu (I was connected with the last character I created and was working before). The problem is the same, it's working once I created my character, but I restarted the server, then ensure : "bcc-utils, bcc-minigames, bcc-ranch" and have nothing on this character

So the char had the ranch before the restart?

**Comment by Phobie53** [comment]
Yes, the character is owner of the ranch and had possibility to use the ranch menu and features. Then I restarted the server for some other scripts. But tested again and had the same issue I had with my first char.

This new created char have no ranch features, it's the owner and the ID of the char in the database is the good one (in table ranch).

**Comment by jakeyboi1** [comment]
> Yes, the character is owner of the ranch and had possibility to use the ranch menu and features. Then I restarted the server for some other scripts. But tested again and had the same issue I had with my first char.
> 
> This new created char have no ranch features, it's the owner and the ID of the char in the database is the good one (in table ranch).

Alright send me a picture of your database aswell as a screen shot of your character from the character db table. Ill give this a test on my end too

**Comment by jakeyboi1** [comment]
I just deleted ranch db and reinstalled the script entirely and it works without a hitch. Tested with a second client to ensure the menu works. It all works well on my end. Delete the ranch db. Reinstall all ranches dependencies and ranch then try
lemme know if that works

**Comment by Phobie53** [comment]
Nevermind it's working again today. I guess it's because I loaded the script and didn't reconnect. Thanks again 🙏
