### ISSUE TITLE
Not opening menu

### ISSUE THREAD

**Issue by Adrianlpe** [BryceCanyonCounty/bcc-ranch#94]
The menu doesn´t shows up when entering the command, the mouse displays but the menu it´s invisible

**Comment by iseeyoucopy** [comment]
In your config do you have manageMyRanchCommand set to true?

**Comment by PremiunServers** [comment]
same problem

**Comment by PremiunServers** [comment]
and i have in true and no open menu and create ranch and i have this problem 
![image](https://github.com/user-attachments/assets/fa9f5f24-b304-4ca8-a416-770536d2f066)

**Comment by Adrianlpe** [comment]
> In your config do you have manageMyRanchCommand set to true?

No, menu doesn´t displays

**Comment by iseeyoucopy** [comment]
You need to set the owner of the ranch, that's why you have that error, make sure all fields are filled up when you create a ranch. To select the owner you have the first option in the menu.....

That's why menu doesn't open. 

We will have a look into this and maybe we will add a notification for each empty field

**Comment by Adrianlpe** [comment]
> You need to set the owner of the ranch, that's why you have that error, make sure all fields are filled up when you create a ranch. To select the owner you have the first option in the menu.....
> 
> That's why menu doesn't open.
> 
> We will have a look into this and maybe we will add a notification for each empty field

My problem comes when I use the `/createRanch` command, the menu doesn´t opens there.

**Comment by iseeyoucopy** [comment]
When we create ranch we never had this issue, make sure you are an admin on to your server, make sure your mariadb database is updated to latest version.

**Comment by Adrianlpe** [comment]
> When we create ranch we never had this issue, make sure you are an admin on to your server, make sure your mariadb database is updated to latest version.

It is updated (reinstaled today), and i´m in admin group

**Comment by iseeyoucopy** [comment]
> > When we create ranch we never had this issue, make sure you are an admin on to your server, make sure your mariadb database is updated to latest version.
> 
> It is updated (reinstaled today), and i´m in admin group
> The menu doesn´t shows up when entering the command, the mouse displays but the menu it´s invisible

make sure you have feather-menu ensured before bcc-ranch

**Comment by iseeyoucopy** [comment]
> and i have in true and no open menu and create ranch and i have this problem ![image](https://private-user-images.githubusercontent.com/177465527/361854558-fa9f5f24-b304-4ca8-a416-770536d2f066.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzIwMTYsIm5iZiI6MTcyNDg3MTcxNiwicGF0aCI6Ii8xNzc0NjU1MjcvMzYxODU0NTU4LWZhOWY1ZjI0LWIzMDQtNGNhOC1hNDE2LTc3MDUzNmQyZjA2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxOTAxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDU1YzAwZTcwNmI4ZmUyNzc3ZmVjNjhkMzhmODc3ZTgwNjBmM2MyNWFhMGZkOTJjYTMwOTAzNGRiMTVmOWFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1RFU6sU0rZVT9tvjrFkXKZfHTFv3U9lgATNxYCNgboY)

I made a new pull request, and that should solve the problem, you didnt set the owner
[https://github.com/BryceCanyonCounty/bcc-ranch/pull/96](url)
