### ISSUE TITLE
No prompt to oben the Ranch Menu with given key when in range to ranch point

### ISSUE THREAD

**Issue by Vajnessa** [BryceCanyonCounty/bcc-ranch#95]
I don't really know why, but when entering the ranch manage zone, no prompt is coming up, telling me or any other to open the ranch menu.

If the setting to open the menu by command, it is working when in the manage zone.

Anyone has or had the same error and knows how to solve it?
Sadly, not the Client nor the Server is throwing an error.
Taking a look into the scripts, i cannot find a possible issue within the code, everything looks clear.

**Comment by iseeyoucopy** [comment]
Make sure  in config manageMyRanchCommand is set on false
